# Generated by Django 5.2.1 on 2025-06-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0002_remove_feedback_comment_remove_feedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
