# Generated by Django 5.2.1 on 2025-06-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0004_subscription_pending_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='active',
            new_name='is_active',
        ),
    ]
