# Generated by Django 5.2.1 on 2025-06-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0005_rename_active_subscription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
