# Generated by Django 5.2.1 on 2025-06-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0006_remove_subscription_is_active_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='total_credit',
            field=models.IntegerField(default=0),
        ),
    ]
